; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: %if x86-registered-target %{ opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux < %s | FileCheck %s %}
; RUN: %if aarch64-registered-target %{ opt -S --passes=slp-vectorizer -mtriple=aarch64-unknown-linux < %s | FileCheck %s %}

define i32 @or_nonzero(ptr nocapture readonly %p) {
; CHECK-LABEL: define i32 @or_nonzero(
; CHECK-SAME: ptr readonly captures(none) [[P:%.*]]) {
; CHECK-NEXT:    [[INPUT:%.*]] = load <8 x i8>, ptr [[P]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne <8 x i8> [[INPUT]], zeroinitializer
; CHECK-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.or.v8i1(<8 x i1> [[TMP1]])
; CHECK-NEXT:    [[RESULT:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[RESULT]]
;
  %input = load <8 x i8>, ptr %p, align 1
  %a0 = extractelement <8 x i8> %input, i64 0
  %a1 = extractelement <8 x i8> %input, i64 1
  %a2 = extractelement <8 x i8> %input, i64 2
  %a3 = extractelement <8 x i8> %input, i64 3
  %a4 = extractelement <8 x i8> %input, i64 4
  %a5 = extractelement <8 x i8> %input, i64 5
  %a6 = extractelement <8 x i8> %input, i64 6
  %a7 = extractelement <8 x i8> %input, i64 7
  %or1 = or i8 %a0, %a1
  %or2 = or i8 %or1, %a2
  %or3 = or i8 %or2, %a3
  %or4 = or i8 %or3, %a4
  %or5 = or i8 %or4, %a5
  %or6 = or i8 %or5, %a6
  %or7 = or i8 %or6, %a7
  %cmp = icmp ne i8 %or7, 0
  %result = zext i1 %cmp to i32
  ret i32 %result
}

define i32 @or_zero(ptr nocapture readonly %p) {
; CHECK-LABEL: define i32 @or_zero(
; CHECK-SAME: ptr readonly captures(none) [[P:%.*]]) {
; CHECK-NEXT:    [[INPUT:%.*]] = load <8 x i8>, ptr [[P]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq <8 x i8> [[INPUT]], zeroinitializer
; CHECK-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.and.v8i1(<8 x i1> [[TMP1]])
; CHECK-NEXT:    [[RESULT:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[RESULT]]
;
  %input = load <8 x i8>, ptr %p, align 1
  %a0 = extractelement <8 x i8> %input, i64 0
  %a1 = extractelement <8 x i8> %input, i64 1
  %a2 = extractelement <8 x i8> %input, i64 2
  %a3 = extractelement <8 x i8> %input, i64 3
  %a4 = extractelement <8 x i8> %input, i64 4
  %a5 = extractelement <8 x i8> %input, i64 5
  %a6 = extractelement <8 x i8> %input, i64 6
  %a7 = extractelement <8 x i8> %input, i64 7
  %or1 = or i8 %a0, %a1
  %or2 = or i8 %or1, %a2
  %or3 = or i8 %or2, %a3
  %or4 = or i8 %or3, %a4
  %or5 = or i8 %or4, %a5
  %or6 = or i8 %or5, %a6
  %or7 = or i8 %or6, %a7
  %cmp = icmp eq i8 %or7, 0
  %result = zext i1 %cmp to i32
  ret i32 %result
}

define i32 @umax_nonzero(ptr nocapture readonly %p) {
; CHECK-LABEL: define i32 @umax_nonzero(
; CHECK-SAME: ptr readonly captures(none) [[P:%.*]]) {
; CHECK-NEXT:    [[INPUT:%.*]] = load <8 x i8>, ptr [[P]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne <8 x i8> [[INPUT]], zeroinitializer
; CHECK-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.or.v8i1(<8 x i1> [[TMP1]])
; CHECK-NEXT:    [[RESULT:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[RESULT]]
;
  %input = load <8 x i8>, ptr %p, align 1
  %a0 = extractelement <8 x i8> %input, i64 0
  %a1 = extractelement <8 x i8> %input, i64 1
  %a2 = extractelement <8 x i8> %input, i64 2
  %a3 = extractelement <8 x i8> %input, i64 3
  %a4 = extractelement <8 x i8> %input, i64 4
  %a5 = extractelement <8 x i8> %input, i64 5
  %a6 = extractelement <8 x i8> %input, i64 6
  %a7 = extractelement <8 x i8> %input, i64 7
  %c1 = icmp ugt i8 %a0, %a1
  %m1 = select i1 %c1, i8 %a0, i8 %a1
  %c2 = icmp ugt i8 %m1, %a2
  %m2 = select i1 %c2, i8 %m1, i8 %a2
  %c3 = icmp ugt i8 %m2, %a3
  %m3 = select i1 %c3, i8 %m2, i8 %a3
  %c4 = icmp ugt i8 %m3, %a4
  %m4 = select i1 %c4, i8 %m3, i8 %a4
  %c5 = icmp ugt i8 %m4, %a5
  %m5 = select i1 %c5, i8 %m4, i8 %a5
  %c6 = icmp ugt i8 %m5, %a6
  %m6 = select i1 %c6, i8 %m5, i8 %a6
  %c7 = icmp ugt i8 %m6, %a7
  %m7 = select i1 %c7, i8 %m6, i8 %a7
  %cmp = icmp ne i8 %m7, 0
  %result = zext i1 %cmp to i32
  ret i32 %result
}

define i32 @umax_zero_commuted(ptr nocapture readonly %p) {
; CHECK-LABEL: define i32 @umax_zero_commuted(
; CHECK-SAME: ptr readonly captures(none) [[P:%.*]]) {
; CHECK-NEXT:    [[INPUT:%.*]] = load <8 x i8>, ptr [[P]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq <8 x i8> [[INPUT]], zeroinitializer
; CHECK-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.and.v8i1(<8 x i1> [[TMP1]])
; CHECK-NEXT:    [[RESULT:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[RESULT]]
;
  %input = load <8 x i8>, ptr %p, align 1
  %a0 = extractelement <8 x i8> %input, i64 0
  %a1 = extractelement <8 x i8> %input, i64 1
  %a2 = extractelement <8 x i8> %input, i64 2
  %a3 = extractelement <8 x i8> %input, i64 3
  %a4 = extractelement <8 x i8> %input, i64 4
  %a5 = extractelement <8 x i8> %input, i64 5
  %a6 = extractelement <8 x i8> %input, i64 6
  %a7 = extractelement <8 x i8> %input, i64 7
  %c1 = icmp ugt i8 %a0, %a1
  %m1 = select i1 %c1, i8 %a0, i8 %a1
  %c2 = icmp ugt i8 %m1, %a2
  %m2 = select i1 %c2, i8 %m1, i8 %a2
  %c3 = icmp ugt i8 %m2, %a3
  %m3 = select i1 %c3, i8 %m2, i8 %a3
  %c4 = icmp ugt i8 %m3, %a4
  %m4 = select i1 %c4, i8 %m3, i8 %a4
  %c5 = icmp ugt i8 %m4, %a5
  %m5 = select i1 %c5, i8 %m4, i8 %a5
  %c6 = icmp ugt i8 %m5, %a6
  %m6 = select i1 %c6, i8 %m5, i8 %a6
  %c7 = icmp ugt i8 %m6, %a7
  %m7 = select i1 %c7, i8 %m6, i8 %a7
  %cmp = icmp eq i8 0, %m7
  %result = zext i1 %cmp to i32
  ret i32 %result
}

define i32 @or_nonzero_multiuse(ptr nocapture readonly %p, ptr %out) {
; CHECK-LABEL: define i32 @or_nonzero_multiuse(
; CHECK-SAME: ptr readonly captures(none) [[P:%.*]], ptr [[OUT:%.*]]) {
; CHECK-NEXT:    [[INPUT:%.*]] = load <8 x i8>, ptr [[P]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[INPUT]])
; CHECK-NEXT:    store i8 [[TMP1]], ptr [[OUT]], align 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i8 [[TMP1]], 0
; CHECK-NEXT:    [[RESULT:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[RESULT]]
;
  %input = load <8 x i8>, ptr %p, align 1
  %a0 = extractelement <8 x i8> %input, i64 0
  %a1 = extractelement <8 x i8> %input, i64 1
  %a2 = extractelement <8 x i8> %input, i64 2
  %a3 = extractelement <8 x i8> %input, i64 3
  %a4 = extractelement <8 x i8> %input, i64 4
  %a5 = extractelement <8 x i8> %input, i64 5
  %a6 = extractelement <8 x i8> %input, i64 6
  %a7 = extractelement <8 x i8> %input, i64 7
  %or1 = or i8 %a0, %a1
  %or2 = or i8 %or1, %a2
  %or3 = or i8 %or2, %a3
  %or4 = or i8 %or3, %a4
  %or5 = or i8 %or4, %a5
  %or6 = or i8 %or5, %a6
  %or7 = or i8 %or6, %a7
  store i8 %or7, ptr %out, align 1
  %cmp = icmp ne i8 %or7, 0
  %result = zext i1 %cmp to i32
  ret i32 %result
}
