; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=vector-combine -S %s | FileCheck %s

declare i8 @llvm.vector.reduce.or.v16i8(<16 x i8>)
declare i8 @llvm.vector.reduce.umax.v16i8(<16 x i8>)

define i1 @or_nonzero(<16 x i8> %x) {
; CHECK-LABEL: define i1 @or_nonzero(
; CHECK-SAME: <16 x i8> [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ne <16 x i8> [[X]], zeroinitializer
; CHECK-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.or.v16i1(<16 x i1> [[TMP0]])
; CHECK-NEXT:    ret i1 [[CMP]]
;
entry:
  %reduction = call i8 @llvm.vector.reduce.or.v16i8(<16 x i8> %x)
  %cmp = icmp ne i8 %reduction, 0
  ret i1 %cmp
}

define i1 @or_zero(<16 x i8> %x) {
; CHECK-LABEL: define i1 @or_zero(
; CHECK-SAME: <16 x i8> [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq <16 x i8> [[X]], zeroinitializer
; CHECK-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.and.v16i1(<16 x i1> [[TMP0]])
; CHECK-NEXT:    ret i1 [[CMP]]
;
entry:
  %reduction = call i8 @llvm.vector.reduce.or.v16i8(<16 x i8> %x)
  %cmp = icmp eq i8 %reduction, 0
  ret i1 %cmp
}

define i1 @umax_nonzero(<16 x i8> %x) {
; CHECK-LABEL: define i1 @umax_nonzero(
; CHECK-SAME: <16 x i8> [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ne <16 x i8> [[X]], zeroinitializer
; CHECK-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.or.v16i1(<16 x i1> [[TMP0]])
; CHECK-NEXT:    ret i1 [[CMP]]
;
entry:
  %reduction = call i8 @llvm.vector.reduce.umax.v16i8(<16 x i8> %x)
  %cmp = icmp ne i8 %reduction, 0
  ret i1 %cmp
}

define i1 @umax_zero_commuted(<16 x i8> %x) {
; CHECK-LABEL: define i1 @umax_zero_commuted(
; CHECK-SAME: <16 x i8> [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq <16 x i8> [[X]], zeroinitializer
; CHECK-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.and.v16i1(<16 x i1> [[TMP0]])
; CHECK-NEXT:    ret i1 [[CMP]]
;
entry:
  %reduction = call i8 @llvm.vector.reduce.umax.v16i8(<16 x i8> %x)
  %cmp = icmp eq i8 0, %reduction
  ret i1 %cmp
}

define i1 @or_nonzero_multiuse(<16 x i8> %x, ptr %out) {
; CHECK-LABEL: define i1 @or_nonzero_multiuse(
; CHECK-SAME: <16 x i8> [[X:%.*]], ptr [[OUT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[REDUCTION:%.*]] = call i8 @llvm.vector.reduce.or.v16i8(<16 x i8> [[X]])
; CHECK-NEXT:    store i8 [[REDUCTION]], ptr [[OUT]], align 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i8 [[REDUCTION]], 0
; CHECK-NEXT:    ret i1 [[CMP]]
;
entry:
  %reduction = call i8 @llvm.vector.reduce.or.v16i8(<16 x i8> %x)
  store i8 %reduction, ptr %out, align 1
  %cmp = icmp ne i8 %reduction, 0
  ret i1 %cmp
}
